export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const LETTERINCREMENT = "LETTERINCREMENT";
export const LETTERDECREMENT = "LETTERDECREMENT";
export const LETTERRESET = "LETTERRESET";
